user-match
WooDongLeee/backend pull request #5
Opened 2022-07-28 10:14 UTC by RyuDongHo

- 전체 api 오류코드 수정

- 용병 신청 api 예외 처리 추가

- 용병 모집글 생성 api 추가

2022-07-28 14:19 UTC, 99kenny requested changes
나머지는 다 괜찮은 것 같습니다.

2022-07-28 14:19 UTC, 99kenny commented on src/main/java/com/woodongleee/src/userMatch/UserMatchController.java
> +    }
이 부분은 머지 할때 빼야 할 것 같아요!

2022-07-28 14:22 UTC, RyuDongHo commented on src/main/java/com/woodongleee/src/userMatch/UserMatchController.java
> +    }
수정하고 머지 해두겠습니다.

2022-07-29 02:16 UTC, 99kenny approved these changes

2022-07-29 02:16 UTC, 99kenny commented on src/main/java/com/woodongleee/src/userMatch/UserMatchController.java
> +    }
넵 수정하고 머지 해주세요~

2022-07-29 04:03 UTC, 99kenny approved these changes

2022-07-29 04:03 UTC, 99kenny commented on src/main/java/com/woodongleee/src/userMatch/UserMatchController.java
> +            userMatchService.applyUserMatch(userIdx, matchPostIdx);
생각해보니까 jwt검증 후 해당 유저의 status도 체크를 해줘야 할 것 같아요 그런데 이 부분은 userProvider의 getUserByJwt를 사용해서 유저정보를 받아온 후 stauts를 체크해주는 식으로 해야 할 것 같은데 아직 getUserByJwt가 없으니 일단 머지 해주시고 다음 pr에 추가해 주시면 좋을 것 같아요!

2022-07-29 04:33 UTC, RyuDongHo commented on src/main/java/com/woodongleee/src/userMatch/UserMatchController.java
> +            userMatchService.applyUserMatch(userIdx, matchPostIdx);
확인했습니다.

2022-07-29 04:33 UTC, merged